_wandb:
    value:
        cli_version: 0.25.1
        e:
            t7fv16gj36ios9nw3w9jlgkf39lmri13:
                email: julianlou2002@gmail.com
                executable: C:\Users\卢俊羽\AppData\Local\Temp\wandb-sync-0251\Scripts\python.exe
                git:
                    commit: b6133692ecec8b476ec82c812a4bc837d237cb7c
                    remote: https://github.com/lu-jun-yu/OPTS.git
                host: Heartunder-Blade
                os: Windows-10-10.0.26200-SP0
                program: <stdin>
                python: CPython 3.10.14
                root: D:\OneDrive - link.tyut.edu.cn\CursorProjects\OPTS
                startedAt: "2026-07-08T09:11:36.220981Z"
                writerId: t7fv16gj36ios9nw3w9jlgkf39lmri13
        m: []
        python_version: 3.10.14
        t:
            "3":
                - 2
                - 13
            "4": 3.10.14
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
