export NCCL_DEBUG=ERROR
export TRANSFORMERS_VERBOSITY=error
export VLLM_LOGGING_LEVEL=WARN

MODEL_SIZE=1.7B
Experiment_Name=reinforce_pp_0322_${MODEL_SIZE}

python3 -m verl.trainer.main_ppo \
 algorithm.adv_estimator=reinforce_plus_plus \
 data.train_files=data/train.parquet \
 data.val_files=data/test.parquet \
 data.train_batch_size=512 \
 data.max_prompt_length=1024 \
 data.max_response_length=2048 \
 data.filter_overlong_prompts=True \
 actor_rollout_ref.model.path=models/Qwen3-${MODEL_SIZE} \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.optim.weight_decay=0.1 \
 actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
 actor_rollout_ref.actor.ppo_mini_batch_size=512 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
 actor_rollout_ref.actor.use_kl_loss=False \
 actor_rollout_ref.rollout.name=vllm \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=256 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.n=4 \
 custom_reward_function.path=utils/reward_fn.py \
 custom_reward_function.name=compute_score \
 algorithm.use_kl_in_reward=False \
 algorithm.kl_ctrl.kl_coef=0.0 \
 trainer.logger='["console","wandb"]' \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.project_name=opts_ttpo_${MODEL_SIZE} \
 trainer.experiment_name=${Experiment_Name} \
 trainer.save_freq=16 \
 trainer.test_freq=8 \
 trainer.total_epochs=10 2>&1 | tee logs/${Experiment_Name}.log